[tool.briefcase]
project_name = "Product Selector"
bundle = "uk.co.codeclear"
version = "0.0.1"
url = "https://codeclear.co.uk/productselector"
license = "BSD license"
author = 'Jon Boland'
author_email = "jon@codeclear.co.uk"

[tool.briefcase.app.productselector]
formal_name = "Product Selector"
description = "Recommends products based on feature requirements"
icon = "src/productselector/resources/productselector"
sources = ['src/productselector']
requires = []


[tool.briefcase.app.productselector.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.productselector.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.productselector.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.productselector.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.productselector.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
